export enum Nature {
    Adamant = 'Adamant',
    Bashful = 'Bashful',
    Bold = 'Bold',
    Brave = 'Brave',
    Calm = 'Calm',
    Careful = 'Careful',
    Docile = 'Docile',
    Gentle = 'Gentle',
    Hardy = 'Hardy',
    Hasty = 'Hasty',
    Impish = 'Impish',
    Jolly = 'Jolly',
    Lax = 'Lax',
    Lonely = 'Lonely',
    Mild = 'Mild',
    Modest = 'Modest',
    Naive = 'Naive',
    Naughty = 'Naughty',
    Quiet = 'Quiet',
    Quirky = 'Quirky',
    Rash = 'Rash',
    Relaxed = 'Relaxed',
    Sassy = 'Sassy',
    Serious = 'Serious',
    Timid = 'Timid',
    None = 'None',
}

export const listOfNatures: Nature[] = [
    Nature.Adamant,
    Nature.Bashful,
    Nature.Bold,
    Nature.Brave,
    Nature.Calm,
    Nature.Careful,
    Nature.Docile,
    Nature.Hardy,
    Nature.Hasty,
    Nature.Impish,
    Nature.Jolly,
    Nature.Lax,
    Nature.Lonely,
    Nature.Mild,
    Nature.Modest,
    Nature.Naive,
    Nature.Naughty,
    Nature.Quiet,
    Nature.Quirky,
    Nature.Rash,
    Nature.Relaxed,
    Nature.Sassy,
    Nature.Serious,
    Nature.Timid,
];